const CHIP_FIELD_MAP = {
  Transmission: "transmission",
  condition: "condition",
  Condition: "condition",
  "Number of Doors": "number_of_doors",
  Purpose: "purpose",
  negotiable: "negotiable",
  Negotiable: "negotiable",
  "For Sale": "for_sale",
  Rentals: "rentals",
  donation: "donation",
  Donation: "donation",
  furnished: "furnished",
  Furnished: "furnished",
  Basement: "basement",
  "Lease Terms": "lease_terms",
  "Credit Score Requirement": "credit_score",
  "Utilities Included": "utilities_included",
  "Access to Amenities": "access_to_amenities",
  "Additional Fees": "additional_fees",
  "Pet Policy": "pet_policy",
  "Renter's Insurance Requirement": "renters_insurance_requirement",
  "Security Measures": "security_measures",
  "Lease Managed By": "lease_managed_by",
  "Bathroom Type": "bathroom_type",
  "Kitchen Access and Type": "kitchen_access_type",
  "Laundry Facilities": "laundry_facilities",
  "Smoking Policy": "smoking_policy",
  "Security Features": "security_features",
  "Preferred Occupants": "preferred_occupants",
  "Mattress Included": "mattress_included",
  "Work Permit": "work_permit",
  "Permit Work": "work_permit",
  "Own Tools Needed": "own_tools",
  "Car Needed": "car_needed",
  Pay: "helper_pay",
  Certification: "certifications",
  Grades: "grades",
  Insurance: "insurance",
  "Payment Options": "payment_options",
  "Types of Cleaning Offered": "cleaning_services",
  "Eco-Friendly Products": "eco_friendly_product",
  "Equipment Provided": "provided_equipment",
  "Specific Services Offered": "handyman_services",
  "Same-Day Service": "same_day_service",
  "Driving Services": "driving_services",
  "Vehicle Type": "vehicle_type",
  "Landscaping Services": "landscaping_services",
  "Regular Maintenance": "regular_maintenance",
  "Seasonal Service": "seasonal_service",
  "Consultancy Services": "consultancy_services",
  "Initial Consultation": "initial_consultation",
  "Services Available": "offered_services",
  "Automation Services": "automation_services",
  "Classes Format": "classes_format",
  "Training Services": "training_services",
  "Session Format": "session_format",
  "Personalized Fitness Plan": "personalised_fitness_plan",
  "Group Sessions": "group_session",
  "Construction Services": "construction_services",
  "Expertise Level": "expertise_level",
  "Technology Services": "technology_services",
  "Service Delivery Method": "service_delivery_method",
  "Ongoing Support": "ongoing_support_maintenance",
  "Visa Services": "visa_services",
  "Free Appointment": "free_appointment",
  "Events Services": "events_services",
  "Customizable Package": "customizable_package",
  "Movers Services": "movers_services",
  "Packing Material": "packing_material",
  "Insurance for Goods": "insurance_for_goods",
  "Farm Services": "farm_services",
  "Delivery Availability": "delivery_availability",
  "Organic Sourced": "organic_sourced",
  "Regular Delivery Option": "regular_delivery_option",
  "Photography Services": "photography_services",
  "Different Packages": "different_packages",
  "Recurring Services": "recurring_services",
  "Interior Services": "interior_services",
  "Material / Furniture Selection": "material_furniture_Selection",
  "Rendering Visualizations": "rendering_visualizations",
  "Homemade Service": "homemade_service",
  "Service Availability": "service_availability",
  "Insurance Service": "insurance_service",
  "Homecare Service": "homecare_service",
  "Menu Customization": "menu_customization",
  "AC Services": "ac_Services",
  "Transport Type": "transport_type",
};

const CHIP_VALUE_MAP = {
  Manual: "MANUAL",
  Automatic: "AUTOMATIC",
  MANUAL: "MANUAL",
  AUTOMATIC: "AUTOMATIC",
  Sale: "SALE",
  Rental: "RENTAL",
  SALE: "SALE",
  RENTAL: "RENTAL",
  Yes: "YES",
  No: "NO",
  YES: "YES",
  NO: "NO",
  NEW: "NEW",
  USED: "USED",
  DURATION: "SHORT-TERM",
  RENEWAL: "LONG-TERM",
  "SHORT-TERM": "SHORT-TERM",
  "LONG-TERM": "LONG-TERM",
  "4": "4/5",
  "3": "1/3",
  "1/3": "1/3",
  "4/5": "4/5",
};

export function chipFieldName(chipGroup) {
  if (chipGroup?.name) return chipGroup.name;
  return CHIP_FIELD_MAP[chipGroup?.label] || chipGroup?.label;
}

export function chipFieldValue(option) {
  if (option && typeof option === "object") {
    return option.value || CHIP_VALUE_MAP[option.label] || option.label;
  }
  return CHIP_VALUE_MAP[option] || option || "";
}

export function chipDisplayLabel(option) {
  if (option && typeof option === "object") {
    return option.label || option.value;
  }
  return option;
}
